[package]
name = "iibhf-devteam/sequencer"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
iibhf-tester = "iibhf-devteam/iibhf-tester@0.1.3"
localaudio = "iitpp-roblox/localaudio@1.5.2"
